# Generated by Django 4.1 on 2023-02-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_remove_housing_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Housing',
        ),
    ]
